### ISSUE TITLE
Tests are too specific?

### ISSUE THREAD

**Issue by soumyaray** [ZhongMeiZhou/scraper_project#36]
Your code looks good!  But I'm worried your tests are looking at data that is very likely to change in the near future (Taiwan tour titles, prices, etc.). Might it not be better just to make sure you are finding some tours without matching the data to stored results?  For example, maybe just check that you've found at least 6 tours, and that they have real prices (numbers), titles (strings), etc.  What do you all think?

**Comment by eduardo-salazar** [comment]
Yes you're right. Is better if we compare the structure instead of the data. Thank you

**Comment by soumyaray** [comment]
I really do appreciate the rigorous testing you've already done though! But yeah, I think the tests need to be made a bit more flexible. Its not a priority for this week's class, but let's try and get it done in the next week or two? Leave a comment here after you've adjusted your tests -- I'll take another look at it before closing the issue.

**Comment by nweat** [comment]
Agreed! Thanks for the advice! Having reviewed it again you are absolutely right. I have began to work on the changes

**Comment by soumyaray** [comment]
:+1:

**Comment by nweat** [comment]
Also I had a question, I wrote a class called ``lonelyplanet_scrap_test.rb``. It was recommended that I implement all functionalities in a test class before moving it to the actual implementation so that is what I was trying to do.  Do you have any thoughts on this?

**Comment by soumyaray** [comment]
Where was it recommended that I implement all functionalities in a test class?  I'm curious.  You might be confusing unit testing with what we are doing (test specifications and more behavior-driven testing)?

**Comment by nweat** [comment]
I believe that would fall under unit testing. I believe they meant that a combination of unit testing and behavior driven testing for example would complement each other. But I just did that class for practice on my own.
